name: Pull Request Triage

on:
  pull_request_target:
    branches: [ main ]

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Print pull request number
        run: echo ${{ github.event.number }}
        
      - name: Print pull request sender
        run: echo ${{ github.event.pull_request.sender }}
      
      - name: Check if the PR requester is a collaborator
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/rafaelfolco/github-ci/collaborators/${{ github.event.pull_request.sender }} \
            --fail
          
