

name: Second Phase Workflow

on:
  workflow_run:
    workflows: ["Pull Request Triage"]
    types:
      - completed
      
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a second test
        run: echo "SECOND TEST"
